<?php
// module/EvlErp/view/evl-erp/products/add.phtml:

namespace EvlErp;

// Le styles
$idx = 100;
$this->headLink()
    ->offsetSetStylesheet(++$idx, $this->basePath() . '/css/module/evl-core/form.css', 'all')
    ->offsetSetStylesheet(++$idx, $this->basePath() . '/css/module/evl-erp/products/add.css', 'all')
    ;

// Scripts
$idx = 100;
$this->bodyScript()
    ->offsetSetFile(++$idx, $this->basePath() . '/js/module/evl-erp/products/add.js')
    ;

$title = $this->translate('Add new product', 'evl-erp');
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php
$form = $this->form;
$form->setAttribute('action', $this->url(
    'erp/products/actions',
    array(
        'locale' => $this->locale,
        'action'=>'add',
    )
));
$form->prepare();
$fieldset = $this->form->get('product');

echo $this->form()->openTag($form);
echo $this->formBootstrapRow($fieldset->get('name'));
echo $this->formBootstrapRow($fieldset->get('category'));
echo $this->formBootstrapRow($fieldset->get('suppliers'));
echo $this->formBootstrapRow($fieldset->get('vat_rate'));
echo $this->formBootstrapRow($fieldset->get('price_netto'));
echo $this->formBootstrapRow($fieldset->get('price_brutto'));
echo $this->formBootstrapRow($fieldset->get('unit'));
echo $this->formBootstrapRow($fieldset->get('description'));

echo '<div class="input-group">';
echo $this->formSubmit($form->get('submit'));
echo $this->formSubmit($form->get('cancel'));
echo '</div>';

echo $this->form()->closeTag();

$this->inlineScript()->captureStart();
?>
var OK = "<?php echo $this->translate('OK', 'evl-core'); ?>";
var valueIsRequired = "<?php echo $this->translate('Value is required and can\'t be empty', 'evl-core'); ?>";
var fieldValueIsInvalid = "<?php echo $this->translate('Field value is invalid', 'evl-erp'); ?>";
var calculatePriceUrl = "<?php echo $this->url('erp/products/ajax-calculate-price', array('locale' => $this->locale)); ?>";
<?php
$this->inlineScript()->captureEnd();
echo $this->inlineScript();
