<?php
// module/EvlErp/view/evl-erp/products/add.phtml:
namespace EvlErp;

$firephp = \FirePHP::getInstance();
$firephp->info($this->locale);

// Le styles
$idx = 100;
$this->headLink()->offsetSetStylesheet(++$idx, $this->basePath() . '/css/module/evl-core/form.css', 'all')
    ->offsetSetStylesheet(++$idx, $this->basePath() . '/css/module/evl-erp/products/add.css', 'all')
    ;

$title = $this->translate('Add new product', 'evl-erp');
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php
$form = $this->form;
$form->setAttribute('action', $this->url(
    'erp/products/actions',
    array(
        'locale' => $this->locale,
        'action'=>'add',
    )
));
$form->prepare();
$fieldset = $this->form->get('product');

echo $this->form()->openTag($form);
echo $this->formBootstrapRow($fieldset->get('name'));
echo $this->formBootstrapRow($fieldset->get('category'));
echo $this->formBootstrapRow($fieldset->get('suppliers'));
echo $this->formBootstrapRow($fieldset->get('vat_rate'));
echo $this->formBootstrapRow($fieldset->get('price_netto'));
echo $this->formBootstrapRow($fieldset->get('price_brutto'));
echo $this->formBootstrapRow($fieldset->get('unit'));
echo $this->formBootstrapRow($fieldset->get('description'));

echo '<div class="input-group">';
echo $this->formSubmit($form->get('submit'));
echo $this->formSubmit($form->get('cancel'));
echo '</div>';

echo $this->form()->closeTag();
