<?php
// module/EvlErp/view/evl-erp/products/add.phtml:

namespace EvlErp;

// Le styles
$idx = 100;
$this->headLink()->offsetSetStylesheet(++$idx, $this->basePath() . '/css/module/evl-core/form.css', 'all')
    ->offsetSetStylesheet(++$idx, $this->basePath() . '/css/module/evl-erp/products/add.css', 'all')
    ;

$title = sprintf($this->translate('Edit: %s'), $this->product->getName());
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php
$form = $this->form;
$form->setAttribute('action', $this->url(
    'erp/products/actions',
    array(
        'locale' => $this->locale,
        'id' => $this->product->getId(),
        'action'=>'edit',
    )
));
$form->prepare();
$fieldset = $this->form->get('product');

echo $this->form()->openTag($form);
echo $this->formBootstrapRow($fieldset->get('name'));
echo $this->formBootstrapRow($fieldset->get('code'));
echo $this->formBootstrapRow($fieldset->get('category'));
echo $this->formBootstrapRow($fieldset->get('suppliers'));
echo $this->formBootstrapRow($fieldset->get('vat_rate'));
echo $this->formBootstrapRow($fieldset->get('price_netto'));
echo $this->formBootstrapRow($fieldset->get('price_brutto'));
echo $this->formBootstrapRow($fieldset->get('unit'));
echo $this->formBootstrapRow($fieldset->get('description'));
echo $this->formBootstrapRow($fieldset->get('created_at'));
echo $this->formBootstrapRow($fieldset->get('updated_at'));

echo '<div class="input-group">';
echo $this->formSubmit($form->get('submit'));
echo $this->formSubmit($form->get('cancel'));
echo '</div>';

echo $this->form()->closeTag();
