<?php
// module/EvlErp/view/evl-erp/vat-rates/add.phtml:

// Le styles
$idx = 100;
$this->headLink()->offsetSetStylesheet(++$idx, $this->basePath() . '/css/module/evl-core/form.css', 'all')
    ->offsetSetStylesheet(++$idx, $this->basePath() . '/css/module/evl-erp/vat-rates/add.css', 'all')
    ;

// Scripts
$idx = 100;
$this->bodyScript()->offsetSetFile(++$idx, $this->basePath() . '/js/vendor/bootstrap/touchspin/2.3.0/bootstrap.touchspin.js')
    ->offsetSetFile(++$idx, $this->basePath() . '/js/module/evl-erp/vat-rates/add.js')
    ;

$title = $this->translate('Add new VAT rate', 'evl-erp');
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php
$form = $this->form;
$form->setAttribute('action', $this->url(
    'erp/vat-rates/actions',
    array(
        'locale' => $this->locale,
        'action'=>'add',
    )
));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formBootstrapRow($form->get('value'));
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();
