<?php
// module/EvlErp/view/evl-erp/vat-rates/index.phtml:
$title = $this->translate('VAT rates list', 'evl-erp');
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
    <a href="<?php echo $this->url('erp/vat-rates/actions', array(
        'locale' => $this->locale,
        'action'=>'add'
    ));?>"><?php echo $this->translate('Add new VAT rate', 'evl-erp'); ?></a>
</p>

<?php if ($vatRates): ?>
<table class="table vat-rates" style="width: 250px;">
<thead>
    <tr>
        <th style="width: 30px;"><?php echo $this->translate('#'); ?></th>
        <th style="width: 40px;"><?php echo $this->translate('ID'); ?></th>
        <th><?php echo $this->translate('Value'); ?></th>
        <th style="width: 80px;">&nbsp;</th>
    </tr>
</thead>
<tbody>
    <?php $idx = 0; ?>
    <?php foreach ($vatRates as $vatRate) : ?>
    <tr>
        <td><?php echo ++$idx; ?></td>
        <td><?php echo $vatRate['id']; ?></td>
        <td><?php echo $this->escapeHtml($vatRate['value']);?>%</td>
        <td>
            <a href="<?php echo $this->url('erp/vat-rates/actions',
                array('locale' => $this->locale, 'action'=>'delete', 'id' => $vatRate['id'])
            );?>"><?php echo $this->translate('Delete'); ?></a>
        </td>
    </tr>
    <?php endforeach; ?>
</tbody>
</table>

<p><?php
$count = count($vatRates);
$message = $this->translatePlural('Found %d VAT rate.', 'Found %d VAT rates.', $count, 'evl-erp-php', $this->locale);
echo sprintf($message, $count);
?></p>
<?php else:?>
<p><?php echo $this->translate('No VAT rate was found.', 'evl-erp'); ?></p>
<?php endif; ?>
