<?php
$this->translate('Edit: %s');

$this->translate('Name');
$this->translate('Description');

$this->translate('Edit');
$this->translate('Delete');
$this->translate('Submit');
$this->translate('Cancel');

$this->translate('Address');
$this->translate('Postcode');
$this->translate('City');
$this->translate('Place');
$this->translate('Country');
$this->translate('Choose country');

$this->translate('Category');
$this->translate('Code');
$this->translate('Price (netto)');
$this->translate('Price (brutto)');

$this->translate('Created at');
$this->translate('Updated at');

// jQuery Data Tables
$this->translate('Show _MENU_ entries');
$this->translate('search for...');
$this->translate('loading data...');
$this->translate('First');
$this->translate('Last');
$this->translate('Next');
$this->translate('Previous');
$this->translate('No data available in table');
