<?php
// module/EvlErp/view/evl-erp/countries/add.phtml:
$firephp = \FirePHP::getInstance();
$firephp->info($this->locale);

// Le styles
$idx = 100;
$this->headLink()->offsetSetStylesheet(++$idx, $this->basePath() . '/css/module/evl-core/form.css', 'all')
    ->offsetSetStylesheet(++$idx, $this->basePath() . '/css/module/evl-erp/countries/add.css', 'all')
    ;

$title = 'Add new country';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php
$form = $this->form;
$form->setAttribute('action', $this->url(
    'erp/countries/actions',
    array(
        'locale' => $this->locale,
        'action'=>'add',
    )
));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formBootstrapRow($form->get('name'));
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();
