<?php echo $this->doctype(); ?>
<?php
// module/Application/view/layout/layout.phtml:
$firephp = \FirePHP::getInstance(true);
$firephp->info($this->locale);
$firephp->info($locale);
?>
<html lang="en">
<head>
  <meta charset="utf-8">
  <?php echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

  <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

  <!-- Le styles -->
  <?php
  $idx = 0;
  echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/favicon.ico'))
            ->offsetSetStylesheet(++$idx, $this->basePath() . '/js/vendor/bootstrap/3.0.3/css/bootstrap.min.css', 'all')
            ->offsetSetStylesheet(++$idx, $this->basePath() . '/js/vendor/bootstrap/3.0.3/css/bootstrap-theme.min.css', 'all')
            ->offsetSetStylesheet(++$idx, $this->basePath() . '/css/module/evl-core/alerts.css')
            ->offsetSetStylesheet(++$idx, $this->basePath() . '/css/style.css')
  ?>

  <!-- Scripts -->
  <?php
  $idx = 0;
//   echo $this->headScript()->offsetSetFile(++$idx, $this->basePath() . '/js/vendor/html5.js', 'text/javascript', array('conditional' => 'lt IE 9'))
  ?>
</head>
<body>
  <div class="ct">
    <div id="top-nav" class="col-md-12" role="main">
      <nav class="navbar navbar-default" role="navigation">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">ZF2 ERP</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li class="active"><a href="<?php echo $this->url('home', array('locale' => $this->locale)); ?>"><?php echo $this->translate('Home') ?></a></li>
            <li><a href=""><?php echo $this->translate('Products') ?></a></li>
            <li><a href=""><?php echo $this->translate('Product categories') ?></a></li>
            <li><a href=""><?php echo $this->translate('Units') ?></a></li>
            <li><a href="<?php echo $this->url('erp/vat-rates', array('locale' => $this->locale)); ?>"><?php echo $this->translate('VAT rates') ?></a></li>
            <li><a href=""><?php echo $this->translate('Suppliers') ?></a></li>
            <?php /*?>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><a href="#">Action</a></li>
                <li><a href="#">Another action</a></li>
                <li><a href="#">Something else here</a></li>
                <li class="divider"></li>
                <li><a href="#">Separated link</a></li>
                <li class="divider"></li>
                <li><a href="#">One more separated link</a></li>
              </ul>
            </li>
            <?php */?>
          </ul>
          <?php /*?>
          <form class="navbar-form navbar-left" role="search">
            <div class="form-group">
              <input type="text" class="form-control" placeholder="Search">
            </div>
            <button type="submit" class="btn btn-default">Submit</button>
          </form>
          <?php */?>
          <div style="margin-top: 8px; float: right;">
          <?php echo $this->partial('layout/languages.phtml', array(
              'locales' => $this->locales,
              'selected' => $this->locale,
          )); ?>
          </div>
        </div><!-- /.navbar-collapse -->
      </nav>
    </div>

    <div class="container">

<?php

if ($this->messages || $this->errors) {
    if (is_array($this->messages)) {
        foreach($this->messages as $message)
        {
            echo '<div class="alert alert-success fade in">' .
                    '<button data-dismiss="alert" class="close" type="button">×</button>' .
                    $message .
                '</div>';
        }
    }

    if (is_array($this->errors)) {
        foreach($this->errors as $error)
        {
            echo '<div class="alert alert-error fade in">' .
                    '<button data-dismiss="alert" class="close" type="button">×</button>' .
                    $error .
                '</div>';
        }
    }
}
?>

      <?php echo $this->content; ?>

      <hr>

      <footer>
      </footer>

    </div> <!-- /container -->
  </div> <!-- /ct -->

<!-- Scripts -->
<?php
$idx = 0;
echo $this->bodyScript()->offsetSetFile(++$idx, $this->basePath() . '/js/vendor/html5.js', 'text/javascript', array('conditional' => 'lt IE 9'))
                        ->offsetSetFile(++$idx, $this->basePath() . '/js/vendor/jquery/1.9.0/jquery.min.js')
                        ->offsetSetFile(++$idx, $this->basePath() . '/js/vendor/bootstrap/3.0.3/js/bootstrap.min.js')
                        ->offsetSetFile(++$idx, $this->basePath() . '/js/core/change-lang.js')
?>
</body>
</html>
