<?php
// module/EvlErp/view/evl-erp/units/add.phtml:

// Le styles
$idx = 100;
$this->headLink()->offsetSetStylesheet(++$idx, $this->basePath() . '/css/module/evl-core/form.css', 'all')
    ->offsetSetStylesheet(++$idx, $this->basePath() . '/css/module/evl-erp/units/add.css', 'all')
    ;

$title = $this->translate('Add new unit', 'evl-erp');
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php
$form = $this->form;
$form->setAttribute('action', $this->url(
    'erp/units/actions',
    array(
        'locale' => $this->locale,
        'action'=>'add',
    )
));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formBootstrapRow($form->get('name'));
echo $this->formBootstrapRow($form->get('description'));
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();
