<?php
// module/EvlErp/view/evl-erp/units/index.phtml:
$firephp = \FirePHP::getInstance();
$firephp->info(__FILE__);
$firephp->info($this->locale);
$title = $this->translate('Units list', 'evl-erp');
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
    <a href="<?php echo $this->url('erp/units/actions', array(
        'locale' => $this->locale,
        'action'=>'add'
    ));?>"><?php echo $this->translate('Add new unit'); ?></a>
</p>

<?php if ($units): ?>
<table class="table units" style="width: 640px;">
<thead>
    <tr>
        <th style="width: 30px;"><?php echo $this->translate('#'); ?></th>
        <th style="width: 40px;"><?php echo $this->translate('ID'); ?></th>
        <th style="width: 50px;"><?php echo $this->translate('Name'); ?></th>
        <th><?php echo $this->translate('Description'); ?></th>
        <th style="width: 80px;">&nbsp;</th>
    </tr>
</thead>
<tbody>
    <?php $idx = 0; ?>
    <?php foreach ($units as $unit) : ?>
    <tr>
        <td><?php echo ++$idx; ?></td>
        <td><?php echo $unit['id']; ?></td>
        <td><?php echo $this->escapeHtml($unit['name']);?></td>
        <td><?php echo $this->escapeHtml($unit['description']);?></td>
        <td>
            <a href="<?php echo $this->url('erp/units/actions',
                array('locale' => $this->locale, 'action'=>'delete', 'id' => $unit['id'])
            );?>"><?php echo $this->translate('Delete'); ?></a>
        </td>
    </tr>
    <?php endforeach; ?>
</tbody>
</table>

<p><?php
$count = count($units);
$message = $this->translatePlural('Found %d unit.', 'Found %d units.', $count, 'evl-erp-php', $this->locale);
echo sprintf($message, $count);
?></p>
<?php else:?>
<p><?php echo $this->translate('No unit was found.', 'evl-erp'); ?></p>
<?php endif; ?>
