<?php
// module/EvlErp/view/evl-erp/companies/index.phtml:
$title = $this->translate('Companies list', 'evl-erp');
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
    <a href="<?php echo $this->url('erp/companies/actions', array(
        'locale' => $this->locale,
        'action'=>'add'
    ));?>"><?php echo $this->translate('Add new company', 'evl-erp'); ?></a>
</p>

<?php if ($companies): ?>
<table class="table companies" style="width: 100%;">
<thead>
    <tr>
        <th style="width: 30px;"><?php echo $this->translate('#'); ?></th>
        <th style="width: 40px;"><?php echo $this->translate('ID'); ?></th>
        <th><?php echo $this->translate('Name'); ?></th>
        <th style="width: 150px;"><?php echo $this->translate('Address'); ?></th>
        <th style="width: 100px;"><?php echo $this->translate('Country'); ?></th>
        <th style="width: 90px;" title="<?php echo $this->translate('VAT Identification Number', 'evl-erp'); ?>">
            <?php echo $this->translate('VATIN', 'evl-erp'); ?>
        </th>
        <th style="width: 90px;" title="<?php echo $this->translate('Enterprise Identification Number', 'evl-erp'); ?>">
            <?php echo $this->translate('EIN', 'evl-erp'); ?>
        </th>
        <th style="width: 90px;" title="<?php echo $this->translate('Business Entity Identification Number', 'evl-erp'); ?>">
            <?php echo $this->translate('BEIN', 'evl-erp'); ?>
        </th>
        <th style="width: 80px;">&nbsp;</th>
    </tr>
</thead>
<tbody>
    <?php $idx = 0; ?>
    <?php foreach ($companies as $company) : ?>
    <tr>
        <td><?php echo ++$idx; ?></td>
        <td><?php echo $company['id']; ?></td>
        <td><?php echo $this->escapeHtml($company['name']);?></td>
        <td>
          <?php echo $this->escapeHtml($company['address']);?><br>
          <?php echo $this->escapeHtml($company['postcode']) . ' ' . $this->escapeHtml($company['city']);?>
        </td>
        <td><?php echo $this->escapeHtml($company['country']['name']);?></td>
        <td><?php echo $this->escapeHtml($company['vatin']);?></td>
        <td><?php echo $this->escapeHtml($company['ein']);?></td>
        <td><?php echo $this->escapeHtml($company['bein']);?></td>
        <td>
            <a href="<?php echo $this->url('erp/companies/actions',
                array('locale' => $this->locale, 'action'=>'delete', 'id' => $company['id'])
            );?>"><?php echo $this->translate('Delete'); ?></a>
        </td>
    </tr>
    <?php endforeach; ?>
</tbody>
</table>

<p><?php
$count = count($companies);
$message = $this->translatePlural('Found %d company.', 'Found %d companies.', $count, 'evl-erp-php', $this->locale);
echo sprintf($message, $count);
?></p>
<?php else:?>
<p><?php echo $this->translate('No company was found.', 'evl-erp'); ?></p>
<?php endif; ?>
